export const companyTypes = [
  "Startup",
  "SaaS (Software as a Service) Provider",
  "Consulting Firm",
  "Digital Agency",
  "Web Development Company",
  "Mobile App Development Company",
  "Cloud Services Provider",
  "Cybersecurity Firm",
  "Data Analytics Company",
  "E-commerce Platform Provider",
  "AI (Artificial Intelligence) Solutions Provider",
  "Blockchain Technology Company",
  "Game Development Studio",
  "IT Infrastructure Services Company",
  "IoT (Internet of Things) Solutions Provider",
  "Managed Services Provider",
  "Big Data Solutions Company",
  "Software Development Outsourcing Firm",
  "Healthtech Startup",
  "Edtech Startup",
];
